// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXazQ8H9qlvg1648XJWWKnVjVmQvR1zFs',
    appId: '1:457854311515:web:74e33d6e1f1b9b432a737e',
    messagingSenderId: '457854311515',
    projectId: 'awesome-gist-403901',
    authDomain: 'awesome-gist-403901.firebaseapp.com',
    databaseURL: 'https://awesome-gist-403901-default-rtdb.firebaseio.com',
    storageBucket: 'awesome-gist-403901.appspot.com',
    measurementId: 'G-WQVC433T9P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjMu7-7PeBwP_n7QRSKcEfH48kQs-TVv4',
    appId: '1:457854311515:android:4c299cf24ec68ff82a737e',
    messagingSenderId: '457854311515',
    projectId: 'awesome-gist-403901',
    databaseURL: 'https://awesome-gist-403901-default-rtdb.firebaseio.com',
    storageBucket: 'awesome-gist-403901.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs6ApXwUEMszEFLv2a1_Aw-gQ_Wc7p73Y',
    appId: '1:457854311515:ios:940ea968301d61952a737e',
    messagingSenderId: '457854311515',
    projectId: 'awesome-gist-403901',
    databaseURL: 'https://awesome-gist-403901-default-rtdb.firebaseio.com',
    storageBucket: 'awesome-gist-403901.appspot.com',
    iosClientId: '457854311515-bc3krha65ssjap5qj61ljvj14imd7cra.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled22',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs6ApXwUEMszEFLv2a1_Aw-gQ_Wc7p73Y',
    appId: '1:457854311515:ios:d9c598bf74fb7fc82a737e',
    messagingSenderId: '457854311515',
    projectId: 'awesome-gist-403901',
    databaseURL: 'https://awesome-gist-403901-default-rtdb.firebaseio.com',
    storageBucket: 'awesome-gist-403901.appspot.com',
    iosClientId: '457854311515-6juhtjj0n0cbap3ela26vd5h7hee6jfl.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled22.RunnerTests',
  );
}
